name: Rust quality test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings" # Make sure CI fails on all warnings, including Clippy lints

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    -name: Run Clippy
      working-directory: ./quality
      run: cargo clippy --all-targets --all-features
    - name: Build
      working-directory: ./quality
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./quality
      run: cargo test --verbose
